[ERROR] Error in View NewSetupView (cogs.systems) 
Traceback (most recent call last):
  File "C:\Users\robin\PycharmProjects\LinkBot\.venv\Lib\site-packages\discord\ui\view.py", line 426, in _scheduled_task
    await item.callback(interaction)
  File "C:\Users\robin\PycharmProjects\LinkBot\cogs\systems.py", line 531, in callback
    await parent_view.advance_step(interaction)
  File "C:\Users\robin\PycharmProjects\LinkBot\cogs\systems.py", line 335, in advance_step
    await self.save_preferences(interaction)
  File "C:\Users\robin\PycharmProjects\LinkBot\cogs\systems.py", line 373, in save_preferences
    await db.execute(
  File "C:\Users\robin\PycharmProjects\LinkBot\.venv\Lib\site-packages\aiosqlite\core.py", line 183, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\robin\PycharmProjects\LinkBot\.venv\Lib\site-packages\aiosqlite\core.py", line 122, in _execute
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\robin\PycharmProjects\LinkBot\.venv\Lib\site-packages\aiosqlite\core.py", line 105, in run
    result = function()
             ^^^^^^^^^^
sqlite3.OperationalError: table servers has no column named preferences
